"""预训练独立入口（框架版）。

说明：
- 该文件只提供预训练流程骨架。
- 不改动现有训练/测试脚本。
- 预训练输出目录与实验模型目录分离：models_pretrain/<dataset>Model/
"""

import argparse
import os
from datetime import datetime

from param_config import dataset_name, model_type


def parse_args():
    parser = argparse.ArgumentParser(description="预训练独立入口（仅流程框架）")
    parser.add_argument("--dataset", default=dataset_name, help="数据集名称")
    parser.add_argument("--model-type", default=model_type, help="模型类型")
    parser.add_argument("--epochs", type=int, default=0, help="预训练轮数（框架占位）")
    parser.add_argument("--save-name", default="", help="预训练文件名（可选，不含后缀）")
    parser.add_argument("--dry-run", action="store_true", help="仅打印流程，不产生占位文件")
    return parser.parse_args()


def ensure_pretrain_dir(dataset):
    root_dir = "models_pretrain"
    dataset_dir = os.path.join(root_dir, "{}Model".format(dataset))
    os.makedirs(dataset_dir, exist_ok=True)
    return dataset_dir


def build_pretrain_context(args, pretrain_dir):
    context = {
        "dataset": args.dataset,
        "model_type": args.model_type,
        "epochs": args.epochs,
        "pretrain_dir": pretrain_dir,
    }
    return context


def run_pretrain_skeleton(context):
    print("=" * 50)
    print("[Pretrain] 预训练框架启动")
    print("[Pretrain] dataset     : {}".format(context["dataset"]))
    print("[Pretrain] model_type  : {}".format(context["model_type"]))
    print("[Pretrain] epochs      : {} (占位参数，未执行真实训练)".format(context["epochs"]))
    print("[Pretrain] output_dir  : {}".format(context["pretrain_dir"]))
    print("[Pretrain] 状态: 框架流程已跑通，真实训练逻辑待接入")
    print("=" * 50)


def resolve_stub_path(args, pretrain_dir):
    if args.save_name:
        base_name = args.save_name
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base_name = "{}_{}_PretrainSkeleton_{}".format(args.dataset, args.model_type, timestamp)
    return os.path.join(pretrain_dir, base_name + ".txt")


def save_pretrain_stub(args, context):
    if args.dry_run:
        print("[Pretrain] dry-run 模式，不写入占位文件")
        return None

    stub_path = resolve_stub_path(args, context["pretrain_dir"])
    with open(stub_path, "w", encoding="utf-8") as f:
        f.write("pretrain_skeleton: true\n")
        f.write("dataset: {}\n".format(context["dataset"]))
        f.write("model_type: {}\n".format(context["model_type"]))
        f.write("epochs: {}\n".format(context["epochs"]))
        f.write("note: this file is generated by pretrain skeleton only.\n")

    print("[Pretrain] 占位文件已保存: {}".format(stub_path))
    return stub_path


def main():
    args = parse_args()
    pretrain_dir = ensure_pretrain_dir(args.dataset)
    context = build_pretrain_context(args, pretrain_dir)
    run_pretrain_skeleton(context)
    save_pretrain_stub(args, context)


if __name__ == "__main__":
    main()
